### ISSUE TITLE
Cleaning up objects from S3 (Textract)

### ISSUE THREAD

**Issue by huge10** [HelgeSverre/extractor#4]
Not a direct issue, but after running into issues with the local PDF parser I quickly went on to use Textract. All works fine after the initial set up, but now I'm wondering what to do with the objects in the bucket. As they are used for a one time operation (Textract extract) maybe it would be nice if the objects get deleted after the operation. Not sure what you think. This can onviously also be achieved in other ways (cron, etc.).

**Comment by HelgeSverre** [comment]
Hmmm i guess we could do this in the package, however, setting up a lifecycle rule on the (textract-specific) bucket that automatically deletes them after 1 day might be more desirable.

As long as that is documented somewhere and people are aware of it, having to setup a lifecycle rule on the bucket seems to me like the better approach.

Needs some time to think about this.

Opinions and suggestions welcome.

**Comment by huge10** [comment]
Agreed on the lifecycle rule. Some people might actually have use cases where they want to keep the files as well. I’ve also been thinking about a way where you might want to reuse a file from the bucket. Again, not sure if this should be part of the package.

**Comment by HelgeSverre** [comment]
Currently the filename i think is randomly generated from an UUID, which might make it impractical to do the cleanup  manually, maybe providing a callback or flag to simply delete the file once it's done is fair enough.


Made a PR with a draft implementation, feedback welcome.

**Comment by HelgeSverre** [comment]
Merged in the PR
